language: python
python: 3.6

install:
- curl https://www.dependencies.io/install.sh | bash -s -- -b $HOME/bin

jobs:
  include:
  - name: test
    script: deps dev test --verbose --loose
  - name: deps
    if: branch = master AND type = cron
    script: deps ci
