sudo: required
services:
  - docker

dist: xenial
language: python
python: 3.7
cache: pip

install:
- pip install dependencies-cli==2.2.4
- curl https://www.dependencies.io/install.sh | bash -s 2.5.0-beta.1

script:
- dependencies test --loose-output-data-comparison
- ./bin/deps dev test --verbose --loose-output-data-comparison
